### PR TITLE
Adding 'has' devdependency in  package.json

### PR DESCRIPTION
**Pull request by siyadava-sindhu**
-->while running test error is coming that says "Cannot find module 'has' because of following line of "ReactEighteenAdapter.js" const has_1 = __importDefault(require("has"));
--> As a fix added 'has' as devdependency

### CODE REVIEW

**Comment by siyadava-sindhu** [comment]
@cfaester  could you please help with review of this PR-changes

**Comment by cfaester** [comment]
Hi @siyadava-sindhu This dep is indeed a "dependency" not a dev. I will create a release with that, but I will have to reject this MR 😄

**Comment by siyadava-sindhu** [comment]
[like]  Sindhusha Yadavalli reacted to your message:
________________________________

**Comment by siyadava-sindhu** [comment]
Thank you so much for adding fix in latest version.

**Pull request closed without merging**
